version: '3.9'

services:
  app:
    container_name: go_app
    build:
      context: .
      dockerfile: go_app.Dockerfile
      target: dev
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mysql
    networks:
      - go_app_network

  mysql:
    image: mysql:8
    container_name: go_mysql
    ports:
      - 3307:3307
    volumes:
      - db_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: test
      MYSQL_DATABASE: go-clean-architecture
      MYSQL_TCP_PORT: 3307
    networks:
      - go_app_network

volumes:
  db_mysql:

networks:
  go_app_network: